-- ─── Full card_reference seed (555 cards) ────────────────────────────────────
-- Run AFTER 002_schema_updates.sql.
-- Clears any existing cards and replaces with the complete set.

TRUNCATE card_reference;

INSERT INTO card_reference (card_name, card_type, tags) VALUES
  ('Colonizer Training Camp', 'Automated', 'Jovian, Building'),
  ('Asteroid Mining Consortium', 'Automated', 'Jovian'),
  ('Deep Well Heating', 'Automated', 'Power, Building'),
  ('Cloud Seeding', 'Automated', NULL),
  ('Search for Life', 'Active', 'Science'),
  ('Inventor’s Guild', 'Active', 'Science'),
  ('Martian Rails', 'Active', 'Building'),
  ('Capital', 'Automated', 'City, Building'),
  ('Asteroid', 'Event', 'Space, Event'),
  ('Comet', 'Event', 'Space, Event'),
  ('Big Asteroid', 'Event', 'Space, Event'),
  ('Water Import From Europa', 'Active', 'Jovian, Space'),
  ('Space Elevator', 'Active', 'Space, Building'),
  ('Development Center', 'Active', 'Science, Building'),
  ('Equatorial Magnetizer', 'Active', 'Building'),
  ('Domed Crater', 'Automated', 'City, Building'),
  ('Noctis City', 'Automated', 'City, Building'),
  ('Methane From Titan', 'Automated', 'Jovian, Space'),
  ('Imported Hydogen', 'Event', 'Earth, Space, Event'),
  ('Research Outpost', 'Active', 'Science, City, Building'),
  ('Phobos Space Haven', 'Automated', 'Space, City'),
  ('Black Polar Dust', 'Automated', NULL),
  ('Arctic Algae', 'Active', 'Plant'),
  ('Predators', 'Active', 'Animal'),
  ('Space Station', 'Active', 'Space'),
  ('Eos Chasma National Park', 'Automated', 'Plant, Building'),
  ('Interstellar Colony Ship', 'Event', 'Earth, Space, Event'),
  ('Security Fleet', 'Active', 'Space'),
  ('Cupola City', 'Automated', 'City, Building'),
  ('Lunar Beam', 'Automated', 'Earth, Power'),
  ('Optimal Aerobraking', 'Active', 'Space'),
  ('Underground City', 'Automated', 'City, Building'),
  ('Regolith Eaters', 'Active', 'Science, Microbe'),
  ('GHG Producing Bacteria', 'Active', 'Science, Microbe'),
  ('Ants', 'Active', 'Microbe'),
  ('Release of Inert Gases', 'Event', 'Event'),
  ('Nitrogen-Rich Asteroid', 'Event', 'Space, Event'),
  ('Rover Construction', 'Active', 'Building'),
  ('Deimos Down', 'Event', 'Space, Event'),
  ('Asteroid Mining', 'Automated', 'Jovian, Space'),
  ('Food Factory', 'Automated', 'Building'),
  ('Archaebacteria', 'Automated', 'Microbe'),
  ('Carbonate Processing', 'Automated', 'Building'),
  ('Natural Perserve', 'Automated', 'Science, Building'),
  ('Nuclear Power', 'Automated', 'Power, Building'),
  ('Lightning Harvest', 'Automated', 'Power'),
  ('Algae', 'Automated', 'Plant'),
  ('Adapted Lichen', 'Automated', 'Plant'),
  ('Tardigrades', 'Active', 'Microbe'),
  ('Virus', 'Event', 'Microbe, Event'),
  ('Miranda Resort', 'Automated', 'Jovian, Space'),
  ('Fish', 'Active', 'Animal'),
  ('Lake Marineris', 'Automated', NULL),
  ('Small Animals', 'Active', 'Animal'),
  ('Kelp Farming', 'Automated', 'Plant'),
  ('Mine', 'Automated', 'Building'),
  ('Vesta Shipyard', 'Automated', 'Jovian, Space'),
  ('Beam From A Thorium Asteroid', 'Automated', 'Jovian, Space, Power'),
  ('Mangrove', 'Automated', 'Plant'),
  ('Trees', 'Automated', 'Plant'),
  ('Great Escarpment Consortium', 'Automated', NULL),
  ('Mineral Deposit', 'Event', 'Event'),
  ('Mining Expedition', 'Event', 'Event'),
  ('Mining Area', 'Automated', 'Building'),
  ('Building Industries', 'Automated', 'Building'),
  ('Land Claim', 'Event', 'Event'),
  ('Mining Rights', 'Automated', 'Building'),
  ('Sponsors', 'Automated', 'Earth'),
  ('Electro Catapult', 'Active', 'Building'),
  ('Earth Catapult', 'Active', 'Earth'),
  ('Advanced Alloys', 'Active', 'Science'),
  ('Birds', 'Active', 'Animal'),
  ('Mars University', 'Active', 'Science, Building'),
  ('Viral Enhancers', 'Active', 'Science, Microbe'),
  ('Towing a Comet', 'Event', 'Space, Event'),
  ('Space Mirrors', 'Active', 'Power, Space'),
  ('Solar Wind Power', 'Automated', 'Science, Space, Power'),
  ('Ice Asteroid', 'Event', 'Space, Event'),
  ('Quantum Extractor', 'Active', 'Science, Power'),
  ('Giant Ice Asteroid', 'Event', 'Space, Event'),
  ('Ganymede Colony', 'Automated', 'Jovian, Space, City'),
  ('Callisto Penal Mines', 'Automated', 'Jovian, Space'),
  ('Giant Space Mirror', 'Automated', 'Power, Space'),
  ('Trans-Neptune Probe', 'Automated', 'Science, Space'),
  ('Commercial District', 'Automated', 'Building'),
  ('Robotic Workforce', 'Automated', 'Science'),
  ('Grass', 'Automated', 'Plant'),
  ('Heather', 'Automated', 'Plant'),
  ('Peroxide Power', 'Automated', 'Power, Building'),
  ('Research', 'Automated', 'Science, Science'),
  ('Gene Repair', 'Automated', 'Science'),
  ('IO Mining Industries', 'Automated', 'Jovian, Space'),
  ('Bushes', 'Automated', 'Plant'),
  ('Mass Converter', 'Active', 'Science, Power'),
  ('Physics Complex', 'Active', 'Science, Building'),
  ('Greenhouses', 'Automated', 'Plant, Building'),
  ('Nuclear Zone', 'Automated', 'Earth'),
  ('Tropical Resort', 'Automated', 'Building'),
  ('Toll Station', 'Automated', 'Space'),
  ('Fueled Generators', 'Automated', 'Power, Building'),
  ('Ironworks', 'Active', 'Building'),
  ('Power Grid', 'Automated', 'Power'),
  ('Steelworks', 'Active', 'Building'),
  ('Ore Processor', 'Active', 'Building'),
  ('Earth Office', 'Active', 'Earth'),
  ('Acquired Company', 'Automated', 'Earth'),
  ('Media Archives', 'Automated', 'Earth'),
  ('Open City', 'Automated', 'City, Building'),
  ('Media Group', 'Active', 'Earth'),
  ('Business Network', 'Active', 'Earth'),
  ('Business Contacts', 'Event', 'Earth, Event'),
  ('Bribed Committee', 'Event', 'Earth, Event'),
  ('Solar Power', 'Automated', 'Power, Building'),
  ('Breathing Filters', 'Automated', 'Science'),
  ('Artificial Photosynthesis', 'Automated', 'Science'),
  ('Artificial Lake', 'Automated', 'Building'),
  ('Geothermal Power', 'Automated', 'Power, Building'),
  ('Farming', 'Automated', 'Plant'),
  ('Dust Seals', 'Automated', NULL),
  ('Urbanized Area', 'Automated', 'City, Building'),
  ('Sabotage', 'Event', 'Event'),
  ('Moss', 'Automated', 'Plant'),
  ('Industrial Center', 'Active', 'Building'),
  ('Hired Raiders', 'Event', 'Event'),
  ('Hackers', 'Automated', NULL),
  ('GHG Factories', 'Automated', 'Building'),
  ('Subterranean Reservoir', 'Event', 'Event'),
  ('Ecological Zone', 'Active', 'Animal, Plant'),
  ('Zeppelins', 'Automated', NULL),
  ('Worms', 'Automated', 'Microbe'),
  ('Decompers', 'Active', 'Microbe'),
  ('Fusion Power', 'Automated', 'Science, Power, Building'),
  ('Symbiotic Fungus', 'Active', 'Microbe'),
  ('Extreme-Cold Fungus', 'Active', 'Microbe'),
  ('Advanced Ecosystems', 'Automated', 'Plant, Microbe, Animal'),
  ('Great Dam', 'Automated', 'Power, Building'),
  ('Cartel', 'Automated', 'Earth'),
  ('Strip Mine', 'Automated', 'Building'),
  ('Wave Power', 'Automated', 'Power'),
  ('Lava Flows', 'Event', 'Event'),
  ('Power Plant', 'Automated', 'Power, Building'),
  ('Mohole Area', 'Automated', 'Building'),
  ('Large Convoy', 'Event', 'Earth, Space, Event'),
  ('Titanium Mine', 'Automated', 'Building'),
  ('Tetonic Stress Power', 'Automated', 'Power, Building'),
  ('Nitrophilic Moss', 'Automated', 'Plant'),
  ('Herbivores', 'Active', 'Animal'),
  ('Insects', 'Automated', 'Microbe'),
  ('CEO''s Favorite Project', 'Event', 'Event'),
  ('Anti-Gravity Technology', 'Active', 'Science'),
  ('Investment Loan', 'Event', 'Earth, Event'),
  ('Insulation', 'Automated', NULL),
  ('Adaption Technology', 'Active', 'Science'),
  ('Caretaker Contract', 'Active', NULL),
  ('Designed Microorganisms', 'Automated', 'Science, Microbe'),
  ('Standard Technology', 'Active', 'Science'),
  ('Nitrite Reducing Bacteria', 'Active', 'Microbe'),
  ('Industrial Microbes', 'Automated', 'Microbe, Building'),
  ('Lichen', 'Automated', 'Plant'),
  ('Power Supply Consortium', 'Automated', 'Power'),
  ('Convoy From Europa', 'Event', 'Space, Event'),
  ('Imported GHG', 'Event', 'Earth, Space, Event'),
  ('Imported Nitrogen', 'Event', 'Earth, Space, Event'),
  ('Micro-Mills', 'Automated', NULL),
  ('Magnetic Field Generators', 'Automated', 'Building'),
  ('Shuttles', 'Active', 'Space'),
  ('Import of Advanced GHG', 'Event', 'Earth, Space, Event'),
  ('Windmills', 'Automated', 'Power, Building'),
  ('Tundra Farming', 'Automated', 'Plant'),
  ('Aerobraked Ammonia Asteroid', 'Event', 'Space, Event'),
  ('Magnetic Field Dome', 'Automated', 'Building'),
  ('Pets', 'Active', 'Earth, Animal'),
  ('Protected Habitats', 'Active', NULL),
  ('Protected Valley', 'Automated', 'Plant, Building'),
  ('Satellites', 'Automated', 'Space'),
  ('Noctis Farming', 'Automated', 'Plant, Building'),
  ('Water Splitting Plant', 'Active', 'Building'),
  ('Heat Trappers', 'Automated', 'Plant, Building'),
  ('Soil Factory', 'Automated', 'Building'),
  ('Fuel Factory', 'Automated', 'Building'),
  ('Ice Cap Melting', 'Event', 'Event'),
  ('Corporate Stronghold', 'Automated', 'City, Building'),
  ('Biomass Combustors', 'Automated', 'Power, Building'),
  ('Livestock', 'Active', 'Animal'),
  ('Olympus Conference', 'Active', 'Science, Earth, Building'),
  ('Rad-Suits', 'Automated', NULL),
  ('Aqufier Pumping', 'Active', 'Building'),
  ('Flooding', 'Event', 'Event'),
  ('Energy Saving', 'Automated', 'Power'),
  ('Local Heat Trapping', 'Event', 'Event'),
  ('Perafrost Extraction', 'Event', 'Event'),
  ('Invention Contest', 'Event', 'Science, Event'),
  ('Plantation', 'Automated', 'Plant'),
  ('Power Infrastructure', 'Active', 'Power, Building'),
  ('Indentured Workers', 'Event', 'Event'),
  ('Lagrange Observatory', 'Automated', 'Science, Space'),
  ('Terraforming Ganymede', 'Automated', 'Jovian, Space'),
  ('Immigration Shuttles', 'Automated', 'Earth, Space'),
  ('Restricted Area', 'Active', 'Science'),
  ('Immigrant City', 'Active', 'City, Building'),
  ('Energy Tapping', 'Automated', 'Power'),
  ('Underground Detonations', 'Active', 'Building'),
  ('Soletta', 'Automated', 'Space'),
  ('Technology Demonstration', 'Event', 'Science, Space, Event'),
  ('Rad-Chem Factory', 'Automated', 'Building'),
  ('Special Design', 'Event', 'Science, Event'),
  ('Medical Lab', 'Automated', 'Science, Building'),
  ('AI Central', 'Active', 'Science, Building'),
  ('Small Asteroid', 'Event', 'Space, Event'),
  ('Self-Replicating Robots', 'Active', NULL),
  ('Snow Algae', 'Automated', 'Plant'),
  ('Penguins', 'Active', 'Animal'),
  ('Aerial Mappers', 'Active', 'Venus'),
  ('Aerosport Tournament', 'Event', 'Event'),
  ('Air-Scrapping Expedition', 'Event', 'Venus, Event'),
  ('Atalanta Planitia Lab', 'Automated', 'Venus, Science'),
  ('Atmoscoop', 'Automated', 'Jovian, Space'),
  ('Comet For Venus', 'Event', 'Space, Event'),
  ('Corroder Suits', 'Automated', 'Venus'),
  ('Dawn City', 'Automated', 'City, Space'),
  ('Deuterium Export', 'Active', 'Space, Venus, Power'),
  ('Dirigibles', 'Active', 'Venus'),
  ('Extractor Balloons', 'Active', 'Venus'),
  ('Extremophiles', 'Active', 'Venus, Microbe'),
  ('Floating Habs', 'Active', 'Venus'),
  ('Forced Precipitation', 'Active', 'Venus'),
  ('Freyja Biodomes', 'Automated', 'Plant, Venus'),
  ('GHG Import From Venus', 'Event', 'Space, Venus, Event'),
  ('Giant Solar Shade', 'Automated', 'Space, Venus'),
  ('Gyropolis', 'Automated', 'City, Building'),
  ('Hydrogen To Venus', 'Event', 'Space, Event'),
  ('IO Sulphur Research', 'Automated', 'Science, Jovian'),
  ('Ishtar Mining', 'Automated', 'Venus'),
  ('Jet Stream Microscrappers', 'Active', 'Venus'),
  ('Local Shading', 'Active', 'Venus'),
  ('Luna Metropolis', 'Automated', 'City, Space, Earth'),
  ('Luxury Foods', 'Automated', NULL),
  ('Maxwell Base', 'Active', 'City, Venus'),
  ('Mining Quota', 'Automated', 'Building'),
  ('Neutralizer Factory', 'Automated', 'Venus'),
  ('Omnicourt', 'Automated', 'Building'),
  ('Orbital Reflectors', 'Automated', 'Venus, Space'),
  ('Rotator Impacts', 'Active', 'Space'),
  ('Sister Planet Support', 'Automated', 'Venus, Earth'),
  ('Solarnet', 'Automated', NULL),
  ('Spin-Inducing Asteroid', 'Event', 'Space, Event'),
  ('Sponsored Academies', 'Automated', 'Earth, Science'),
  ('Stratopolis', 'Active', 'City, Venus'),
  ('Stratospheric Birds', 'Active', 'Venus, Animal'),
  ('Sulphur Exports', 'Automated', 'Venus, Space'),
  ('Sulphur-Eating Bacteria', 'Active', 'Venus, Microbe'),
  ('Terraforming Contract', 'Automated', 'Earth'),
  ('Thermophiles', 'Active', 'Venus, Microbe'),
  ('Water To Venus', 'Event', 'Space, Event'),
  ('Venus Governor', 'Automated', 'Venus, Venus'),
  ('Venus Magnetizer', 'Active', 'Venus'),
  ('Venus Soils', 'Automated', 'Venus, Plant'),
  ('Venus Waystation', 'Active', 'Venus, Space'),
  ('Venusian Animals', 'Active', 'Venus, Animal, Science'),
  ('Venusian Insects', 'Active', 'Venus, Microbe'),
  ('Venusian Plants', 'Automated', 'Venus, Plant'),
  ('Allied Banks', 'Prelude', 'Earth'),
  ('Aquifer Turbines', 'Prelude', 'Power'),
  ('Biofuels', 'Prelude', 'Microbe'),
  ('Biolab', 'Prelude', 'Science'),
  ('Biosphere Support', 'Prelude', 'Plant'),
  ('Business Empire', 'Prelude', 'Earth'),
  ('Dome Farming', 'Prelude', 'Plant, Building'),
  ('Donation', 'Prelude', NULL),
  ('Early Settlement', 'Prelude', 'Building, City'),
  ('Ecology Experts', 'Prelude', 'Plant, Microbe'),
  ('Excentric Sponsor', 'Prelude', NULL),
  ('Experimental Forest', 'Prelude', 'Plant'),
  ('Galilean Mining', 'Prelude', 'Jovian'),
  ('Great Aquifer', 'Prelude', NULL),
  ('Huge Asteroid', 'Prelude', NULL),
  ('IO Research Outpost', 'Prelude', 'Jovian, Science'),
  ('Loan', 'Prelude', NULL),
  ('Martian Industries', 'Prelude', 'Building'),
  ('Metal-Rich Asteroid', 'Prelude', NULL),
  ('Metals Company', 'Prelude', NULL),
  ('Mining Operations', 'Prelude', 'Building'),
  ('Mohole', 'Prelude', 'Building'),
  ('Mohole Excavation', 'Prelude', 'Building'),
  ('Nitrogen Shipment', 'Prelude', NULL),
  ('Orbital Construction Yard', 'Prelude', 'Space'),
  ('Polar Industries', 'Prelude', 'Building'),
  ('Power Generation', 'Prelude', 'Power'),
  ('Research Network', 'Prelude', 'Wild'),
  ('Self-Sufficient Settlement', 'Prelude', 'Building, City'),
  ('Smelting Plant', 'Prelude', 'Building'),
  ('Society Support', 'Prelude', NULL),
  ('Supplier', 'Prelude', 'Power'),
  ('Supply Drop', 'Prelude', NULL),
  ('UMNI Contractor', 'Prelude', 'Earth'),
  ('Acquired Space Agency', 'Prelude', NULL),
  ('House Printing', 'Automated', 'Building'),
  ('Lava Tube Settlement', 'Automated', 'Building, City'),
  ('Martian Survey', 'Event', 'Science, Event'),
  ('Psychrophiles', 'Active', 'Microbe'),
  ('Research Coordination', 'Automated', 'Wild'),
  ('SF Memorial', 'Automated', 'Building'),
  ('Space Hotels', 'Automated', 'Space, Earth'),
  ('Applied Science', 'Prelude', 'Wild'),
  ('Atmospheric Enhancers', 'Prelude', 'Venus'),
  ('Board of Directors', 'Prelude', 'Earth'),
  ('Colony Trade Hub', 'Prelude', 'Space'),
  ('Corridors of Power', 'Prelude', 'Earth'),
  ('Early Colonization', 'Prelude', 'Space'),
  ('Floating Trade Hub', 'Prelude', 'Space'),
  ('Focused Organization', 'Prelude', NULL),
  ('High Circles', 'Prelude', 'Earth'),
  ('Industrial Complex', 'Prelude', 'Building'),
  ('Main Belt Asteroids', 'Prelude', 'Space'),
  ('Nobel Prize', 'Prelude', 'Wild'),
  ('Old Mining Colony', 'Prelude', 'Space'),
  ('Planetary Alliance', 'Prelude', 'Earth, Jovian, Venus'),
  ('Preservation Program', 'Prelude', NULL),
  ('Project Eden', 'Prelude', 'City, Plant'),
  ('Recession', 'Prelude', NULL),
  ('Rise To Power', 'Prelude', NULL),
  ('Soil Bacteria', 'Prelude', 'Microbe'),
  ('Space Lanes', 'Prelude', 'Space'),
  ('Suitable Infrastructure', 'Prelude', 'Building'),
  ('Terraforming Deal', 'Prelude', 'Earth'),
  ('Venus Contract', 'Prelude', 'Venus'),
  ('Venus L1 Shade', 'Prelude', 'Space'),
  ('World Government Advisor', 'Prelude', 'Earth'),
  ('Ceres Tech Market', 'Active', 'Science'),
  ('Cloud Tourism', 'Active', 'Jovian, Venus'),
  ('Colonial Envoys', 'Event', 'Event'),
  ('Colonial Representation', 'Active', NULL),
  ('Envoys From Venus', 'Event', 'Venus, Event'),
  ('Floating Refinery', 'Active', 'Venus'),
  ('Frontier Town', 'Automated', 'City, Building'),
  ('GHG Shipment', 'Event', 'Space, Event'),
  ('Ishtar Expedition', 'Event', 'Venus, Event'),
  ('Jovian Envoys', 'Event', 'Event'),
  ('L1 Trade Terminal', 'Active', 'Space'),
  ('Microgravity Nutrition', 'Automated', 'Microbe, Plant'),
  ('Red Appeasment', 'Event', 'Event'),
  ('Soil Studies', 'Event', 'Microbe, Plant, Event'),
  ('Special Permit', 'Event', 'Plant, Event'),
  ('Sponsoring Nation', 'Automated', 'Earth'),
  ('Stratospheric Expedition', 'Event', 'Venus, Space, Event'),
  ('Summit Logistics', 'Automated', 'Building, Space'),
  ('Unexpected Application', 'Event', 'Venus, Space'),
  ('Venus Allies', 'Automated', 'Venus, Space'),
  ('Venus Orbital Survey', 'Active', 'Venus, Space'),
  ('Venus Shuttles', 'Active', 'Venus'),
  ('Venus Trade Hub', 'Active', 'Venus, Space'),
  ('WG Project', 'Automated', 'Earth'),
  ('Airliners', 'Automated', NULL),
  ('Air Raid', 'Event', 'Event'),
  ('Atmo Collectors', 'Active', NULL),
  ('Community Services', 'Automated', NULL),
  ('Conscription', 'Event', 'Earth, Event'),
  ('Corona Extractor', 'Automated', 'Space, Power'),
  ('Cryo Sleep', 'Active', 'Science'),
  ('Earth Elevator', 'Automated', 'Space, Earth'),
  ('Ecology Research', 'Automated', 'Science, Plant, Animal, Microbe'),
  ('Floater Leasing', 'Automated', NULL),
  ('Floater Prototypes', 'Event', 'Science, Event'),
  ('Floater Technology', 'Active', 'Science'),
  ('Galilean Waystation', 'Automated', 'Space'),
  ('Heavy Texation', 'Automated', 'Earth'),
  ('Ice Moon Colony', 'Automated', 'Space'),
  ('Impactor Swarm', 'Event', 'Space, Event'),
  ('Interplanetary Colony Ship', 'Event', 'Space, Earth, Event'),
  ('Jovian Lanterns', 'Active', 'Jovian'),
  ('Jupiter Floating Station', 'Active', 'Jovian'),
  ('Luna Governor', 'Automated', 'Earth, Earth'),
  ('Lunar Exports', 'Automated', 'Earth, Space'),
  ('Lunar Mining', 'Automated', 'Earth'),
  ('Market Manipulation', 'Event', 'Earth, Event'),
  ('Martian Zoo', 'Active', 'Animal, Building'),
  ('Mining Colony', 'Automated', 'Space'),
  ('Minority Refuge', 'Automated', 'Space'),
  ('Molecular Printing', 'Automated', 'Science'),
  ('Nitrogen From Titan', 'Automated', 'Jovian, Space'),
  ('Pioneer Settlement', 'Automated', 'Space'),
  ('Productive Outpost', 'Automated', NULL),
  ('Quantum Communications', 'Automated', NULL),
  ('Red Spot Observatory', 'Active', 'Jovian, Science'),
  ('Refugee Camps', 'Active', 'Earth'),
  ('Research Colony', 'Automated', 'Space, Science'),
  ('Rim Freighters', 'Active', 'Space'),
  ('Sky Dokcs', 'Active', 'Space, Earth'),
  ('Solar Probe', 'Event', 'Space, Science, Event'),
  ('Solar Reflectors', 'Automated', 'Space'),
  ('Space Port', 'Automated', 'City, Building'),
  ('Space Port Colony', 'Automated', 'Space'),
  ('Spin-Off Department', 'Active', 'Building'),
  ('Sub-Zero Salt Fish', 'Active', 'Animal'),
  ('Titan Air-Scrapping', 'Active', 'Jovian'),
  ('Titan Floating Launch-Pad', 'Active', 'Jovian'),
  ('Titan Shuttles', 'Active', 'Jovian, Space'),
  ('Trade Envoys', 'Active', NULL),
  ('Trading Colony', 'Active', 'Space'),
  ('Urban Decomposers', 'Automated', 'Microbe'),
  ('Warp Drive', 'Active', 'Science'),
  ('Aerial Lenses', 'Automated', NULL),
  ('Banned Delegate', 'Event', 'Event'),
  ('Cultural Metropolis', 'Automated', 'City, Building'),
  ('Diaspora Movement', 'Automated', 'Jovian'),
  ('Event Analysts', 'Active', 'Science'),
  ('GMO Contract', 'Active', 'Microbe, Science'),
  ('Martian Media Center', 'Active', 'Building'),
  ('Parliament Hall', 'Automated', 'Building'),
  ('PR Office', 'Automated', 'Earth'),
  ('Public Celebrations', 'Event', 'Event'),
  ('Recruitment', 'Event', 'Event'),
  ('Red Tourism Wave', 'Event', 'Earth, Event'),
  ('Sponsored Mohole', 'Automated', 'Building'),
  ('Supported Research', 'Automated', 'Science'),
  ('Wildlife Dome', 'Automated', 'Animal, Plant, Building'),
  ('Vote Of No Confidence', 'Event', 'Event'),
  ('Dusk Laser Mining', 'Automated', 'Space'),
  ('Project Inspection', 'Event', 'Event'),
  ('Energy Market', 'Active', 'Power'),
  ('HI-Tech Lab', 'Active', 'Science, Building'),
  ('Interplanetary Trade', 'Automated', 'Space'),
  ('Law Suit', 'Event', 'Earth, Event'),
  ('Mercurian Alloys', 'Active', 'Space'),
  ('Orbial Cleanup', 'Active', 'Earth, Space'),
  ('Political Alliance', 'Event', 'Event'),
  ('Rego Plastics', 'Active', 'Building'),
  ('Saturn Surfing', 'Active', 'Jovian, Earth'),
  ('Stanford Torus', 'Automated', 'Space, City'),
  ('Advertising', 'Active', 'Earth'),
  ('Asteroid Delflection System', 'Active', 'Space, Earth, Building'),
  ('Asteroid Hollowing', 'Active', 'Space'),
  ('Comet Aiming', 'Active', 'Space'),
  ('Crash Site Cleanup', 'Event', 'Event'),
  ('Cutting Edge Technology', 'Active', 'Science'),
  ('Directed Impactors', 'Active', 'Space'),
  ('Diversity Support', 'Event', 'Event'),
  ('Field-Capped City', 'Automated', 'City, Building, Power'),
  ('Imported Nutrients', 'Event', 'Earth, Space, Event'),
  ('Jovian Embassy', 'Automated', 'Jovian, Building'),
  ('Magnetic Shield', 'Automated', 'Space'),
  ('Meat Industries', 'Active', 'Building'),
  ('Meltworks', 'Active', 'Building'),
  ('Mohole Lake', 'Active', 'Building'),
  ('Potatoes', 'Automated', 'Plant'),
  ('Sub-Crust Measurements', 'Active', 'Science, Building, Earth'),
  ('Topsoil Contract', 'Active', 'Microbe, Earth'),
  ('Deimos Down [Promo]', 'Event', 'Space, Event'),
  ('Great Damn [Promo]', 'Automated', 'Power, Building'),
  ('Magnetic Field Generators [Promo]', 'Automated', 'Building'),
  ('Asteroid Rights', 'Active', 'Earth, Space'),
  ('Bactoviral Research', 'Automated', 'Microbe, Science'),
  ('Bio Printing Facility', 'Active', 'Building'),
  ('Harvest', 'Event', 'Plant, Event'),
  ('Outdoor Sports', 'Automated', NULL),
  ('Corporate Archives', 'Prelude', 'Science'),
  ('Double Down', 'Prelude', NULL),
  ('Merger', 'Prelude', NULL),
  ('New Partner', 'Prelude', NULL),
  ('Head Start', 'Prelude', NULL),
  ('16 Psych', 'Automated', 'Space'),
  ('Robot Pollinators', 'Automated', NULL),
  ('Supercapacitors', 'Active', 'Power, Building'),
  ('Icy Impactors', 'Active', 'Space'),
  ('Directed Heat Usage', 'Active', NULL),
  ('Anti-Desertification Techniques', 'Prelude', 'Microbe, Plant'),
  ('Aqueduct Systems', 'Automated', 'Building'),
  ('Astra Mechanica', 'Automated', 'Science'),
  ('Carbon Systems', 'Active', 'Science, Building'),
  ('Cyberia Systems', 'Automated', NULL),
  ('Established Methods', 'Prelude', NULL),
  ('Giant Solar Collector', 'Prelude', 'Space'),
  ('Hermetic Order Of Mars', 'Automated', NULL),
  ('Homeostasis Bureau', 'Active', 'Building'),
  ('Kaguya Tech', 'Automated', 'City, Plant'),
  ('Mars Nomads', 'Active', NULL),
  ('Martian Lumber Corp', 'Active', 'Building, Plant'),
  ('Neptunian Power Consultans', 'Active', 'Power'),
  ('Red Ships', 'Active', NULL),
  ('Solar Logistics', 'Active', 'Earth, Space'),
  ('St. Joseph Of Cupertino Mission', 'Active', NULL),
  ('Strategic Base Planning', 'Prelude', 'City, Building, Space'),
  ('Teslaract', 'Active', 'Power, Building'),
  ('Soil Enrichment', 'Event', 'Microbe, Plant, Event'),
  ('Supermarkets', 'Automated', NULL),
  ('Hospitals', 'Active', 'Building'),
  ('Public Paths', 'Automated', 'Building'),
  ('City Parks', 'Automated', 'Plant'),
  ('Casinos', 'Automated', 'Building'),
  ('Protected Growth', 'Event', 'Plant, Event'),
  ('Static Harvesting', 'Automated', 'Power'),
  ('Vermin', 'Active', 'Microbe, Animal'),
  ('Public Plans', 'Event', 'Event'),
  ('Albedo Plants', 'Prelude', 'Plant'),
  ('Credicor', 'Corporation', NULL),
  ('Ecoline', 'Corporation', 'Plant'),
  ('Helion', 'Corporation', 'Space'),
  ('Mining Guild', 'Corporation', 'Building, Building'),
  ('Interplanetary Cinematics', 'Corporation', 'Building'),
  ('Inventrix', 'Corporation', 'Science'),
  ('Phobolog', 'Corporation', 'Space'),
  ('Tharsis Republic', 'Corporation', 'Building'),
  ('Thorgate', 'Corporation', 'Power'),
  ('United Nations Mars Initiative', 'Corporation', 'Earth'),
  ('Teractor', 'Corporation', 'Earth'),
  ('Saturn Systems', 'Corporation', 'Jovian'),
  ('Aphrodite', 'Corporation', 'Plant, Venus'),
  ('Celestic', 'Corporation', 'Venus'),
  ('Manutech', 'Corporation', 'Building'),
  ('Morning Star Inc.', 'Corporation', 'Venus'),
  ('Viron', 'Corporation', 'Microbe'),
  ('Cheung Shing Mars', 'Corporation', 'Building'),
  ('Point Luna', 'Corporation', 'Space, Earth'),
  ('Robinson Industries', 'Corporation', NULL),
  ('Valley Trust', 'Corporation', 'Earth'),
  ('Vitor', 'Corporation', 'Earth'),
  ('Aridor', 'Corporation', NULL),
  ('Arklight', 'Corporation', 'Animal'),
  ('Polyphemos', 'Corporation', NULL),
  ('Poseidon', 'Corporation', NULL),
  ('StormCraft Incorporated', 'Corporation', 'Jovian'),
  ('Lakefront Resorts', 'Corporation', 'Building'),
  ('Pristar', 'Corporation', NULL),
  ('Septem Tribus', 'Corporation', 'Wild'),
  ('Terralabs Research', 'Corporation', 'Science, Earth'),
  ('Utopia Invest', 'Corporation', 'Building'),
  ('Factorum', 'Corporation', 'Power, Building'),
  ('Mons Insurance', 'Corporation', NULL),
  ('Philares', 'Corporation', 'Building'),
  ('Arcadian Communites', 'Corporation', NULL),
  ('Recylon', 'Corporation', 'Microbe, Building'),
  ('Splice Tactical Genomics', 'Corporation', 'Microbe'),
  ('Astrodrill', 'Corporation', 'Space'),
  ('Pharmacy Union', 'Corporation', 'Microbe, Microbe'),
  ('Kuiper Cooperative', 'Corporation', 'Space, Space'),
  ('Tycho Magnetics', 'Corporation', 'Power, Science'),
  ('EcoTec', 'Corporation', 'Microbe, Plant'),
  ('Nirgal Enterprises', 'Corporation', 'Power, Plant, Building'),
  ('Paladin Shipping', 'Corporation', 'Space'),
  ('Sagitta', 'Corporation', NULL),
  ('Spire', 'Corporation', 'City, Earth'),
  ('PolderTECH Duth', 'Corporation', 'Earth'),
  ('Floyd Continuum', 'Active', 'Science'),
  ('New Holland', 'Automated', 'City, Building'),
  ('Bioengineering Enclosure', 'Active', 'Animal'),
  ('Bio-Fertilizer Facility', 'Automated', 'Microbe, Building'),
  ('Butterfly Effect', 'Event', 'Event'),
  ('Desperate Measures', 'Event', 'Event'),
  ('Ecological Survey', 'Active', 'Science'),
  ('Geological Survey', 'Active', 'Science'),
  ('Marketing Experts', 'Active', 'Earth'),
  ('Metallic Asteroid', 'Event', 'Space, Event'),
  ('Ocean City', 'Automated', 'City, Building'),
  ('Ocean Farm', 'Automated', 'Plant, Building'),
  ('Ocean Sanctuary', 'Automated', 'Animal')
ON CONFLICT (card_name) DO NOTHING;
