-- ─── Seed card_reference from tm-cardreference-tags.csv ──────────────────────
-- Run after 001_initial_schema.sql.
-- Expansion is inferred: Venus Next cards added at row ~214 (Aerial Mappers onwards).
-- Base VP is left null for now — fill in as needed.

insert into card_reference (card_name, tags, card_type, expansion) values
('Colonizer Training Camp',    'Building, Jovian',          'Automated', null),
('Asteroid Mining Consortium', 'Jovian',                    'Automated', null),
('Deep Well Heating',          'Building, Power',           'Automated', null),
('Cloud Seeding',              null,                        'Automated', null),
('Search for Life',            'Science',                   'Active',    null),
('Inventor''s Guild',          'Science',                   'Active',    null),
('Martian Rails',              'Building',                  'Active',    null),
('Capital',                    'Building, City',            'Automated', null),
('Asteroid',                   'Event, Space',              'Event',     null),
('Comet',                      'Event, Space',              'Event',     null),
('Big Asteroid',               'Event, Space',              'Event',     null),
('Water Import From Europa',   'Jovian, Space',             'Active',    null),
('Space Elevator',             'Building, Space',           'Active',    null),
('Development Center',         'Building, Science',         'Active',    null),
('Equatorial Magnetizer',      'Building',                  'Active',    null),
('Domed Crater',               'Building, City',            'Automated', null),
('Noctis City',                'Building, City',            'Automated', null),
('Methane From Titan',         'Jovian, Space',             'Automated', null),
('Imported Hydrogen',          'Earth, Event, Space',       'Event',     null),
('Research Outpost',           'Building, City, Science',   'Active',    null),
('Phobos Space Haven',         'City, Space',               'Automated', null),
('Black Polar Dust',           null,                        'Automated', null),
('Arctic Algae',               'Plant',                     'Active',    null),
('Predators',                  'Animal',                    'Active',    null),
('Space Station',              'Space',                     'Active',    null),
('Eos Chasma National Park',   'Building, Plant',           'Automated', null),
('Interstellar Colony Ship',   'Earth, Event, Space',       'Event',     null),
('Security Fleet',             'Space',                     'Active',    null),
('Cupola City',                'Building, City',            'Automated', null),
('Lunar Beam',                 'Earth, Power',              'Automated', null),
('Optimal Aerobraking',        'Space',                     'Active',    null),
('Underground City',           'Building, City',            'Automated', null),
('Regolith Eaters',            'Microbe, Science',          'Active',    null),
('GHG Producing Bacteria',     'Microbe, Science',          'Active',    null),
('Ants',                       'Microbe',                   'Active',    null),
('Release of Inert Gases',     'Event',                     'Event',     null),
('Nitrogen-Rich Asteroid',     'Event, Space',              'Event',     null),
('Rover Construction',         'Building',                  'Active',    null),
('Deimos Down',                'Event, Space',              'Event',     null),
('Asteroid Mining',            'Jovian, Space',             'Automated', null),
('Food Factory',               'Building',                  'Automated', null),
('Archaebacteria',             'Microbe',                   'Automated', null),
('Carbonate Processing',       'Building',                  'Automated', null),
('Natural Preserve',           'Science',                   'Automated', null),
('Nuclear Power',              'Building, Power',           'Automated', null),
('Lightning Harvest',          'Power',                     'Automated', null),
('Algae',                      'Plant',                     'Automated', null),
('Adapted Lichen',             'Plant',                     'Automated', null),
('Tardigrades',                'Microbe',                   'Active',    null),
('Virus',                      'Event, Microbe',            'Event',     null),
('Miranda Resort',             'Jovian, Space',             'Automated', null),
('Fish',                       'Animal',                    'Active',    null),
('Lake Marineris',             null,                        'Automated', null),
('Small Animals',              'Animal',                    'Active',    null),
('Kelp Farming',               'Plant',                     'Automated', null),
('Mine',                       'Building',                  'Automated', null),
('Vesta Shipyard',             'Jovian, Space',             'Automated', null),
('Beam From A Thorium Asteroid','Jovian, Power, Space',     'Automated', null),
('Mangrove',                   'Plant',                     'Automated', null),
('Trees',                      'Plant',                     'Automated', null),
('Great Escarpment Consortium','Building',                  'Automated', null),
('Mineral Deposit',            'Event',                     'Event',     null),
('Mining Expedition',          'Event',                     'Event',     null),
('Mining Area',                'Building',                  'Automated', null),
('Building Industries',        'Building, Earth, Event',    'Automated', null),
('Land Claim',                 'Event',                     'Event',     null),
('Mining Rights',              'Building',                  'Automated', null),
('Sponsors',                   'Earth',                     'Automated', null),
('Electro Catapult',           'Building',                  'Active',    null),
('Earth Catapult',             'Earth',                     'Active',    null),
('Advanced Alloys',            'Science',                   'Active',    null),
('Birds',                      'Animal',                    'Active',    null),
('Mars University',            'Building, Science',         'Active',    null),
('Viral Enhancers',            'Microbe, Science',          'Active',    null),
('Towing a Comet',             'Event, Space',              'Event',     null),
('Space Mirrors',              'Power, Space',              'Active',    null),
('Solar Wind Power',           'Power, Science, Space',     'Automated', null),
('Ice Asteroid',               'Event, Space',              'Event',     null),
('Quantum Extractor',          'Power, Science',            'Active',    null),
('Giant Ice Asteroid',         'Event, Space',              'Event',     null),
('Ganymede Colony',            'City, Jovian, Space',       'Automated', null),
('Callisto Penal Mines',       'Jovian, Science',           'Automated', null),
('Giant Space Mirror',         'Power, Space',              'Automated', null),
('Trans-Neptune Probe',        'Science, Space',            'Automated', null),
('Commercial District',        'Building',                  'Automated', null),
('Robotic Workforce',          'Science',                   'Automated', null),
('Grass',                      'Plant',                     'Automated', null),
('Heather',                    'Plant',                     'Automated', null),
('Peroxide Power',             'Building, Power',           'Automated', null),
('Research',                   'Science',                   'Automated', null),
('Gene Repair',                'Science',                   'Automated', null),
('IO Mining Industries',       'Jovian, Space',             'Automated', null),
('Bushes',                     'Plant',                     'Automated', null),
('Mass Converter',             'Power, Science',            'Active',    null),
('Physics Complex',            'Building, Science',         'Active',    null),
('Greenhouses',                'Building, Plant',           'Automated', null),
('Nuclear Zone',               'Earth',                     'Automated', null),
('Tropical Resort',            'Building',                  'Automated', null),
('Toll Station',               'Space',                     'Automated', null),
('Fueled Generators',          'Building, Power',           'Automated', null),
('Ironworks',                  'Building',                  'Active',    null),
('Power Grid',                 'Power',                     'Automated', null),
('Steelworks',                 'Building',                  'Active',    null),
('Ore Processor',              'Building',                  'Active',    null),
('Earth Office',               'Earth',                     'Active',    null),
('Acquired Company',           'Earth',                     'Automated', null),
('Media Archives',             'Earth',                     'Automated', null),
('Open City',                  'Building, City',            'Automated', null),
('Media Group',                'Earth',                     'Active',    null),
('Business Network',           'Earth',                     'Active',    null),
('Business Contacts',          'Earth',                     'Event',     null),
('Bribed Committee',           'Earth, Event',              'Event',     null),
('Solar Power',                'Building, Power',           'Automated', null),
('Breathing Filters',          'Science',                   'Automated', null),
('Artificial Photosynthesis',  'Science',                   'Automated', null),
('Artificial Lake',            'Building',                  'Automated', null),
('Geothermal Power',           'Building, Power',           'Automated', null),
('Farming',                    'Animal, Plant',             'Automated', null),
('Dust Seals',                 null,                        'Automated', null),
('Urbanized Area',             'Building, City',            'Automated', null),
('Sabotage',                   'Event',                     'Event',     null),
('Moss',                       'Plant',                     'Automated', null),
('Industrial Center',          'Building',                  'Active',    null),
('Hired Raiders',              'Event',                     'Event',     null),
('Hackers',                    null,                        'Automated', null),
('GHG Factories',              'Building',                  'Automated', null),
('Subterranean Reservoir',     'Event',                     'Event',     null),
('Ecological Zone',            'Animal, Microbe',           'Active',    null),
('Zeppelins',                  null,                        'Automated', null),
('Worms',                      'Microbe',                   'Automated', null),
('Decomposers',                'Microbe',                   'Active',    null),
('Fusion Power',               'Building, Power, Science',  'Automated', null),
('Symbiotic Fungus',           'Microbe',                   'Active',    null),
('Extreme-Cold Fungus',        'Microbe',                   'Active',    null),
('Advanced Ecosystems',        'Animal, Microbe, Plant',    'Automated', null),
('Great Dam',                  'Building, Power',           'Automated', null),
('Cartel',                     'Earth',                     'Automated', null),
('Strip Mine',                 'Building',                  'Automated', null),
('Wave Power',                 'Power',                     'Automated', null),
('Lava Flows',                 'Event',                     'Event',     null),
('Power Plant',                'Building, Power',           'Automated', null),
('Mohole Area',                'Building',                  'Automated', null),
('Large Convoy',               'Earth, Event, Space',       'Event',     null),
('Titanium Mine',              'Building',                  'Automated', null),
('Tectonic Stress Power',      'Building, Power',           'Automated', null),
('Nitrophilic Moss',           'Plant',                     'Automated', null),
('Herbivores',                 'Animal',                    'Active',    null),
('Insects',                    'Microbe',                   'Automated', null),
('CEO''s Favorite Project',    'Event',                     'Event',     null),
('Anti-Gravity Technology',    'Science',                   'Active',    null),
('Investment Loan',            'Earth, Event',              'Event',     null),
('Insulation',                 null,                        'Automated', null),
('Adaptation Technology',      'Science',                   'Active',    null),
('Caretaker Contract',         null,                        'Active',    null),
('Designed Microorganisms',    'Microbe, Science',          'Automated', null),
('Standard Technology',        'Science',                   'Active',    null),
('Nitrite Reducing Bacteria',  'Microbe',                   'Active',    null),
('Industrial Microbes',        'Microbe',                   'Automated', null),
('Lichen',                     'Plant',                     'Automated', null),
('Power Supply Consortium',    'Power',                     'Automated', null),
('Convoy From Europa',         'Event, Space',              'Event',     null),
('Imported GHG',               'Earth, Event, Space',       'Event',     null),
('Imported Nitrogen',          'Earth, Event, Space',       'Event',     null),
('Micro-Mills',                null,                        'Automated', null),
('Magnetic Field Generators',  'Building',                  'Automated', null),
('Shuttles',                   'Space',                     'Active',    null),
('Import of Advanced GHG',     'Earth, Event, Space',       'Event',     null),
('Windmills',                  'Building, Power',           'Automated', null),
('Tundra Farming',             'Plant',                     'Automated', null),
('Aerobraked Ammonia Asteroid','Event, Space',              'Event',     null),
('Magnetic Field Dome',        'Building',                  'Automated', null),
('Pets',                       'Animal, Earth',             'Active',    null),
('Protected Habitats',         null,                        'Active',    null),
('Protected Valley',           'Building, Plant',           'Automated', null),
('Satellites',                 'Space',                     'Automated', null),
('Noctis Farming',             'Building, Plant',           'Automated', null),
('Water Splitting Plant',      'Building',                  'Active',    null),
('Heat Trappers',              'Building, Power',           'Automated', null),
('Soil Factory',               'Building',                  'Automated', null),
('Fuel Factory',               'Building',                  'Automated', null),
('Ice Cap Melting',            'Event',                     'Event',     null),
('Corporate Stronghold',       'Building, City',            'Automated', null),
('Biomass Combustors',         'Building, Power',           'Automated', null),
('Livestock',                  'Animal',                    'Active',    null),
('Olympus Conference',         'Building, Earth, Science',  'Active',    null),
('Rad-Suits',                  null,                        'Automated', null),
('Aquifer Pumping',            'Building',                  'Active',    null),
('Flooding',                   'Event',                     'Event',     null),
('Energy Saving',              'Power',                     'Automated', null),
('Local Heat Trapping',        'Event',                     'Event',     null),
('Permafrost Extraction',      'Event',                     'Event',     null),
('Invention Contest',          'Event',                     'Event',     null),
('Plantation',                 'Plant',                     'Automated', null),
('Power Infrastructure',       'Building, Power',           'Active',    null),
('Indentured Workers',         'Event',                     'Event',     null),
('Lagrange Observatory',       'Science, Space',            'Automated', null),
('Terraforming Ganymede',      'Jovian, Space',             'Automated', null),
('Immigrant Shuttles',         'Earth, Event, Space',       'Automated', null),
('Restricted Area',            'Science',                   'Active',    null),
('Immigrant City',             'Building, City',            'Active',    null),
('Energy Tapping',             'Power',                     'Automated', null),
('Underground Detonations',    'Building',                  'Active',    null),
('Soletta',                    'Space',                     'Automated', null),
('Technology Demonstration',   'Earth, Science, Space',     'Event',     null),
('Rad-Chem Factory',           'Building',                  'Automated', null),
('Special Design',             'Event, Science',            'Event',     null),
('Medical Lab',                'Building, Science',         'Automated', null),
('AI Central',                 'Building, Science',         'Active',    null),
('Small Asteroid',             'Event, Space',              'Event',     null),
('Self-Replicating Robots',    null,                        'Active',    null),
('Snow Algae',                 'Plant',                     'Automated', null),
('Penguins',                   'Animal',                    'Active',    null),
-- Venus Next expansion
('Aerial Mappers',             'Venus',                     'Active',    'Venus Next'),
('Aerosport Tournament',       'Event',                     'Event',     'Venus Next'),
('Air-Scrapping Expedition',   'Event, Venus',              'Event',     'Venus Next'),
('Atalanta Planitia Lab',      'Science, Venus',            'Automated', 'Venus Next'),
('Atmoscoop',                  'Jovian, Space',             'Automated', 'Venus Next'),
('Comet For Venus',            'Event, Space',              'Event',     'Venus Next'),
('Corroder Suits',             'Venus',                     'Automated', 'Venus Next'),
('Dawn City',                  'City, Space',               'Automated', 'Venus Next'),
('Deuterium Export',           'Power, Space, Venus',       'Active',    'Venus Next'),
('Dirigibles',                 'Venus',                     'Active',    'Venus Next'),
('Extractor Balloons',         'Venus',                     'Active',    'Venus Next'),
('Extremophiles',              'Microbe, Venus',            'Active',    'Venus Next'),
('Floating Habs',              'Venus',                     'Active',    'Venus Next'),
('Forced Precipitation',       'Venus',                     'Active',    'Venus Next'),
('Freyja Biodomes',            'Plant, Venus',              'Automated', 'Venus Next'),
('GHG Import From Venus',      'Event, Space, Venus',       'Event',     'Venus Next'),
('Giant Solar Shade',          'Space, Venus',              'Automated', 'Venus Next'),
('Gyropolis',                  'Building, City',            'Automated', 'Venus Next'),
('Hydrogen To Venus',          'Event, Space',              'Event',     'Venus Next'),
('IO Sulphur Research',        'Jovian, Science',           'Automated', 'Venus Next'),
('Ishtar Mining',              'Venus',                     'Automated', 'Venus Next'),
('Jet Stream Microscrappers',  'Venus',                     'Active',    'Venus Next'),
('Local Shading',              'Venus',                     'Active',    'Venus Next'),
('Luna Metropolis',            'City, Earth, Space',        'Automated', 'Venus Next'),
('Luxury Foods',               null,                        'Automated', 'Venus Next'),
('Maxwell Base',               'City, Venus',               'Active',    'Venus Next'),
('Mining Quota',               'Building',                  'Automated', 'Venus Next'),
('Neutralizer Factory',        'Venus',                     'Automated', 'Venus Next'),
('Omnicourt',                  'Building',                  'Automated', 'Venus Next'),
('Orbital Reflectors',         'Space, Venus',              'Automated', 'Venus Next'),
('Rotator Impacts',            'Space',                     'Active',    'Venus Next'),
('Sister Planet Support',      'Earth, Venus',              'Automated', 'Venus Next'),
('Solarnet',                   null,                        'Automated', 'Venus Next'),
('Spin-Inducing Asteroid',     'Event, Space',              'Event',     'Venus Next'),
('Sponsored Academies',        'Earth, Science',            'Automated', 'Venus Next'),
('Stratopolis',                'City, Venus',               'Active',    'Venus Next'),
('Stratospheric Birds',        'Animal, Venus',             'Active',    'Venus Next'),
('Sulphur Exports',            'Space, Venus',              'Automated', 'Venus Next'),
('Sulphur-Eating Bacteria',    'Microbe, Venus',            'Active',    'Venus Next'),
('Terraforming Contract',      'Earth',                     'Automated', 'Venus Next'),
('Thermophiles',               'Microbe, Venus',            'Active',    'Venus Next'),
('Water To Venus',             'Space, Venus',              'Event',     'Venus Next'),
('Venus Governor',             'Venus',                     'Automated', 'Venus Next')
on conflict (card_name) do nothing;
